services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./local_storage:/app/local_storage
      - ./app:/app/app
    environment:
      - MODELS_DIR=/app/models
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/photo_validation
    depends_on:
      - db
    command: >
      bash -c "
        # Ждем, пока PostgreSQL запустится
        echo 'Waiting for PostgreSQL...'
        while ! pg_isready -h db -p 5432 -q; do
          sleep 1
        done
        echo 'PostgreSQL is up - executing migrations'
        # Применяем миграции
        alembic upgrade head
        # Запускаем приложение
        uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
      "

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=photo_validation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
