# Конфигурация проверок фотографий
# Автоматически сгенерирована из метаданных модулей
# Изменения администратора сохраняются при перезапуске

'# Автоматически сгенерированная конфигурация': из метаданных модулей проверки
check_order:
- face_count
- accessories
- face_pose
- face_position
- blurriness
- color_mode
- lighting
- real_photo
- red_eye
- background
- extraneous_objects
checks:
  accessories:
    enabled: true
    params:
      glasses_confidence_threshold: 0.5
      glasses_detection_enabled: false
      hand_detection_enabled: true
      headwear_detection_enabled: true
      skin_detection_threshold: 0.5
  background:
    enabled: true
    params:
      background_std_dev_threshold: 110.0
      edge_density_threshold: 0.08
      grad_mean_threshold: 45
      is_dark_threshold: 80
  blurriness:
    enabled: true
    params:
      laplacian_threshold: 40
  color_mode:
    enabled: true
    params:
      grayscale_saturation_threshold: 15
      require_color: true
  extraneous_objects:
    enabled: true
    params:
      canny_threshold1: 50
      canny_threshold2: 150
      min_object_contour_area_ratio: 0.03
      person_min_neighbors: 6
      person_scale_factor: 1.1
  face_count:
    enabled: true
    params:
      face_confidence_threshold: 0.45
      max_count: 1
      min_count: 1
  face_pose:
    enabled: true
    params:
      max_pitch: 25.0
      max_roll: 25.0
      max_yaw: 25.0
  face_position:
    enabled: true
    params:
      boundary_tolerance: 5
      face_center_tolerance: 0.4
      face_max_area_ratio: 0.8
      face_min_area_ratio: 0.05
      min_height_ratio: 0.2
      min_margin_ratio: 0.03
      min_width_ratio: 0.15
  lighting:
    enabled: true
    params:
      highlight_ratio_threshold: 0.3
      low_contrast_threshold: 20
      overexposure_threshold: 240
      shadow_ratio_threshold: 0.4
      underexposure_threshold: 25
  real_photo:
    enabled: true
    params:
      color_distribution_threshold: 50
      evidence_bias: photo
      gradient_mean_threshold: 20
      mid_freq_energy_threshold: 250
      texture_var_threshold: 1.5
  red_eye:
    enabled: true
    params:
      adaptive_threshold: true
      debug_mode: false
      hsv_detection: true
      min_red_pixel_ratio: 0.15
      pupil_relative_size: 0.3
      red_ratio_threshold: 1.8
      red_threshold: 180
      save_debug_images: false
system:
  max_check_time: 5.0
  stop_on_failure: false
