"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=True),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_validation_requests_request_id'), 'validation_requests', ['request_id'], unique=False)
    op.create_index('ix_validation_requests_checks_gin', 'validation_requests', ['checks'], unique=False, postgresql_using='gin')
    op.create_index('ix_validation_requests_issues_gin', 'validation_requests', ['issues'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_validation_requests_issues_gin', table_name='validation_requests')
    op.drop_index('ix_validation_requests_checks_gin', table_name='validation_requests')
    op.drop_index(op.f('ix_validation_requests_request_id'), table_name='validation_requests')
    op.drop_table('validation_requests')
    # ### end Alembic commands ### 