"""Add filename and file_size to validation_requests

Revision ID: 002_add_filename_filesize
Revises: 001
Create Date: 2025-05-24 18:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_add_filename_filesize'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_requests', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('validation_requests', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_requests', 'file_size')
    op.drop_column('validation_requests', 'filename')
    # ### end Alembic commands ### 