"""Initial migration

Revision ID: b05bc1155193
Revises: 
Create Date: 2025-04-30 20:59:05.908563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b05bc1155193'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=True),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('ix_validation_requests_checks_gin', 'validation_requests', ['checks'], unique=False, postgresql_using='gin')
    op.create_index('ix_validation_requests_issues_gin', 'validation_requests', ['issues'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_validation_requests_request_id'), 'validation_requests', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_requests_request_id'), table_name='validation_requests')
    op.drop_index('ix_validation_requests_issues_gin', table_name='validation_requests', postgresql_using='gin')
    op.drop_index('ix_validation_requests_checks_gin', table_name='validation_requests', postgresql_using='gin')
    op.drop_table('validation_requests')
    # ### end Alembic commands ###
